### ISSUE TITLE
Shader problems

### ISSUE THREAD

**Issue by JekSun97** [GEG-fairbear8974/PSX-Style-Camera-Shader#3]
I noticed that Color Limination works strangely, in the camera preview the shader does what is expected, but when starting the game, the flowers are cut to a small value, and it is not possible to achieve the desired effect.

In preview (good):
![1](https://github.com/user-attachments/assets/ccd1938f-d515-4941-a705-e7367406d9f8)

when starting the game (bad):
![2](https://github.com/user-attachments/assets/6e449fca-4f39-4953-aefe-fb96e10a8911)

I also noticed that if we set the Noise Time value to 0.1, the noise seems to accelerate then slow down, I fixed this in the shader by removing the SIN function in TIME, which I advise you to do:
`float hashOld12(vec2 p){
	return fract(sin(dot(p, vec2(12.9898, 78.233))) * 43758.5453 + (TIME / noise_time_fac)) ;
}`

It would also be great if they could implement vertex swing, that is, when the vertex points do not move smoothly.
And the shader is wonderful, thank you!

**Comment by immaculate-lift-studio** [comment]
Thanks for the feedback @JekSun97. I think it's because the scene doesn't have a worldenvironment so when you run it there isn't any source of light (in the editor it works because of the editor-specific settings). I will keep this issue open and try to push a version with a worldenvironment and light source so this isn't a problem.

That next version will also have your code fix in it. Appreciate the help!

**Comment by immaculate-lift-studio** [comment]
The fixes took about 2 minutes. Pushed an update so check the releases for the fixes.
